### ISSUE TITLE
Clarify role of clap-log-flag vs. clap-verbosity-flag

### ISSUE THREAD

**Issue by dimo414** [rust-clique/clap-log-flag#8]
It's not clear to me why there's separate repos for clap-verbosity-flag and clap-log-flag. It appears this repo uses clap-verbosity-flag internally, but it also seems to have not been updated in a number of years. What's the intended use case(s) for these different repos? Could their functionality be merged and the other retired?

**Comment by epage** [comment]
`clap-log-flag` has logger-specific policy while `clap-verbosity-flag` only relies on `log` and can work with any logger.

`clap-log-flag` has not been any attention.  The original author has moved on and i personally prefer not maintaining so much policy but leaving it to the user.

**Comment by dimo414** [comment]
Should this repo be archived then? Or at least update the repo to call out these differences and possibly discourage its use? As-is this project looks more "official" than clap-verbosity-flag e.g. by looking at the README.

**Comment by epage** [comment]
I was considering it.  Going ahead.
